
export const CommonConstants = {
    // USER STATUSES
     USER_STATUS_NEW :'NEW',
     USER_STATUS_AVAILABLE :'AVAILABLE',
     USER_STATUS_LOCKED  : 'LOCKED',

     // USER TYPES
     USER_TYPES_OWNER :'OWNER',
     USER_TYPES_RENTER : 'RENTER',
     USER_TYPES_OWNER_N_RENTER : 'OWNER_N_RENTER',
     USER_TYPES_MGMT : 'MGMT',
     USER_TYPES_PROP_DEV : 'PROP_DEV',

     // PROPERTY TYPES
     PROPERTY_STATUS_NEW : 'NEW',
     PROPERTY_STATUS_AVAILABLE : 'AVAILABLE',
     PROPERTY_STATUS_LOCKED : 'LOCKED'
};